sources:
  - name: OryxLayouts
    handler:
      graphql:
        endpoint: https://oryx.zsa.io/graphql
        operationHeaders:
          Authorization: Bearer {env.TOKEN}

serve:
  browser: false
  
documents:
  - ./src/**/*.graphql

sdk:
  generateOperations:
    selectionSetDepth: 3 # This is the maximum level of selection set